// <auto-generated />
using System;
using Bjj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bjj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230127081850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Bjj.Models.Fight", b =>
                {
                    b.Property<int>("FightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfFight")
                        .HasColumnType("TEXT");

                    b.Property<int>("FightResultById")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<int>("Fighter1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Fighter2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("WeightCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.HasKey("FightId");

                    b.HasIndex("FightResultById");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Fight");
                });

            modelBuilder.Entity("Bjj.Models.FightResultBy", b =>
                {
                    b.Property<int>("FightResultById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FightResultById");

                    b.ToTable("FightResultBy");
                });

            modelBuilder.Entity("Bjj.Models.Fighter", b =>
                {
                    b.Property<int>("FighterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeltColour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("FighterId");

                    b.ToTable("Fighter");
                });

            modelBuilder.Entity("Bjj.Models.Fight", b =>
                {
                    b.HasOne("Bjj.Models.FightResultBy", "FightResultBy")
                        .WithMany()
                        .HasForeignKey("FightResultById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjj.Models.Fighter", "Fighter1")
                        .WithMany("Fighters1")
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjj.Models.Fighter", "Fighter2")
                        .WithMany("Fighters2")
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjj.Models.Fighter", "Winner")
                        .WithMany("Winners")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FightResultBy");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Bjj.Models.Fighter", b =>
                {
                    b.Navigation("Fighters1");

                    b.Navigation("Fighters2");

                    b.Navigation("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
